server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  client:
    # Disable registration and fetching because this is the server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/